### ISSUE TITLE
Convert timestamps like "20151130" to datetime.date in eia.py

### ISSUE THREAD

**Issue by epogrebnyak** [epogrebnyak/fx-oil#3]
```year, month, day = split_timestamp("20151130")```

**Comment by sinancetinkaya** [comment]
objDate = datetime.strptime("20151130", "%Y%m%d")
year, month, day = [objDate.year, objDate.month, objDate.day]

**Comment by epogrebnyak** [comment]
Very explicit, thanks!
7 дек. 2015 г. 20:09 пользователь "Sinan Çetinkaya" <
notifications@github.com> написал:
